# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41cf49087cec0d6aecf795486c40fe475a751ac21ff56aa9c7c42807070b1f11a166c497540cecc8ade135a432488b2b5d268c12d74653e67b5a44ff6237524b

test:
  secret_key_base: feb3c9568fdbd463503508793092a9810ed038b3ac7544aa744404db292e1d462cde14188991fe52fd0b8342d144ad576cc77e5620035707af81f071ab3042d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
